version: '3.9'

services:
  order_service:
    image: ${ORDER_APP_NAME}:${ORDER_APP_VERSION}
    env_file:
        - .env
    ports:
      - ${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=order
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
    networks:
      - backend


networks:
  backend:    

volumes:
  mongodb:

  
